### ISSUE TITLE
String inside of String interpolation can make a file unparseable

### ISSUE THREAD

**Issue by chadmoone** [sleekbyte/tailor#351] opened 2016-03-22 23:19 UTC
The following code inside of any swift file will cause Tailor to be unable to parse the entire file:

```swift
print("Hello \(optionalString ?? "Earth")")
```
Results in:

```bash
$ tailor Test.swift

********** /Users/user/development/Test.swift **********
Test.swift could not be parsed successfully, skipping...

Analyzed 0 files, skipped 1 file, and detected 0 violations (0 errors, 0 warnings).
```

**Comment by alykhank** [comment] 2016-03-23 01:43
Thanks for reporting! Closing as a duplicate of #278, a new release containing this fix will be out shortly.

**Closed by alykhank** 2016-03-23 01:43 UTC
Labels: duplicate
