### ISSUE TITLE
Support for more granular control over naming

### ISSUE THREAD

**Issue by jeeftor** [sleekbyte/tailor#365] opened 2016-04-19 17:37 UTC
I would love to have the ability to enforce naming conventions on only "some" things such as

* classes
* structs
* functions
* enums 

etc.

Our specific use case is that we are still using c-style THIS_IS_AN_ENUM for our enums - and thus we get a lot errors we don't intent to fix

**Comment by alykhank** [comment] 2016-04-19 18:28
Closing as duplicate of #366.

**Closed by alykhank** 2016-04-19 18:28 UTC
